version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: sevgidocker/reverseproxy 
  backend_user:
    build:
      context: ../../udacity-c2-restapi-user
    image: sevgidocker/udacity-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c2-restapi-feed  
    image: sevgidocker/udacity-restapi-feed
  frontend:
    build:
      context: ../../udacity-c2-frontend  
    image: sevgidocker/udacity-frontend:local